// forum comment
export const GET_FORUM_COMMENT = 'GET_FORUM_COMMENT';
export const GET_FORUM_COMMENT_SUCCESS = 'GET_FORUM_COMMENT_SUCCESS';
export const GET_FORUM_COMMENT_FAIL = 'GET_FORUM_COMMENT_FAIL';

export const CREATE_FORUM_COMMENT = 'CREATE_FORUM_COMMENT';
export const CREATE_FORUM_COMMENT_SUCCESS = 'CREATE_FORUM_COMMENT_SUCCESS';
export const CREATE_FORUM_COMMENT_FAIL = 'CREATE_FORUM_COMMENT_FAIL';
// forum post
export const GET_FORUM_POST = 'GET_FORUM_POST';
export const GET_FORUM_POST_SUCCESS = 'GET_FORUM_POST_SUCCESS';
export const GET_FORUM_POST_FAIL = 'GET_FORUM_POST_FAIL';
