/*
 *
 * Home constants
 *
 */
// category
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
// subCategory
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_SUB_CATEGORY_SUCCESS = 'GET_SUB_CATEGORY_SUCCESS';
export const GET_SUB_CATEGORY_FAIL = 'GET_SUB_CATEGORY_FAIL';

export const GET_SUB_CATEGORY_BY_CID = 'GET_SUB_CATEGORY_BY_CID';
export const GET_SUB_CATEGORY_BY_CID_SUCCESS =
  'GET_SUB_CATEGORY_BY_CID_SUCCESS';
export const GET_SUB_CATEGORY_BY_CID_FAIL = 'GET_SUB_CATEGORY_BY_CID_FAIL';
// contact
export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL';
// lastestPost
export const GET_LASTEST_POST = 'GET_LASTEST_POST';
export const GET_LASTEST_POST_SUCCESS = 'GET_LASTEST_POST_SUCCESS';
export const GET_LASTEST_POST_FAIL = 'GET_LASTEST_POST_FAIL';

export const GET_LASTEST_POST_BY_SCID = 'GET_LASTEST_POST_BY_SCID';
export const GET_LASTEST_POST_BY_SCID_SUCCESS =
  'GET_LASTEST_POST_BY_SCID_SUCCESS';
export const GET_LASTEST_POST_BY_SCID_FAIL = 'GET_LASTEST_POST_BY_SCID_FAIL';
// postBySubCategory
export const GET_LASTEST_POST_BSC = 'GET_LASTEST_POST_BSC';
export const GET_LASTEST_POST_BSC_SUCCESS = 'GET_LASTEST_POST_BSC_SUCCESS';
export const GET_LASTEST_POST_BSC_FAIL = 'GET_LASTEST_POST_BSC_FAIL';
// report
export const CREATE_PROBLEM = 'CREATE_PROBLEM';
export const CREATE_PROBLEM_SUCCESS = 'CREATE_PROBLEM_SUCCESS';
export const CREATE_PROBLEM_FAIL = 'CREATE_PROBLEM_FAIL';
// document
export const GET_LASTEST_DOCUMENT = 'GET_LASTEST_DOCUMENT';
export const GET_LASTEST_DOCUMENT_SUCCESS = 'GET_LASTEST_DOCUMENT_SUCCESS';
export const GET_LASTEST_DOCUMENT_FAIL = 'GET_LASTEST_DOCUMENT_FAIL';
// weather
export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL';

export const GET_CITY_LIST = 'GET_CITY_LIST';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_FAIL = 'GET_CITY_LIST_FAIL';
// login
export const GET_LOGIN_TOKEN = 'GET_LOGIN_TOKEN';
export const GET_LOGIN_TOKEN_SUCCESS = 'GET_LOGIN_TOKEN_SUCCESS';
export const GET_LOGIN_TOKEN_FAIL = 'GET_LOGIN_TOKEN_FAIL';
// banner
export const GET_BANNER = 'GET_BANNER';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_FAIL = 'GET_BANNER_FAIL';
// token
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAIL = 'CHECK_TOKEN_FAIL';
// user
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
// forumPost
export const GET_FORUM_POST_BY_UID = 'GET_FORUM_POST_BY_UID';
export const GET_FORUM_POST_BY_UID_SUCCESS = 'GET_FORUM_POST_BY_UID_SUCCESS';
export const GET_FORUM_POST_BY_UID_FAIL = 'GET_FORUM_POST_BY_UID_FAIL';
