/*
 *
 * Home constants
 *
 */
// category
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
// subCategory
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_SUB_CATEGORY_SUCCESS = 'GET_SUB_CATEGORY_SUCCESS';
export const GET_SUB_CATEGORY_FAIL = 'GET_SUB_CATEGORY_FAIL';

export const GET_SUB_CATEGORY_BY_CID = 'GET_SUB_CATEGORY_BY_CID';
export const GET_SUB_CATEGORY_BY_CID_SUCCESS =
  'GET_SUB_CATEGORY_BY_CID_SUCCESS';
export const GET_SUB_CATEGORY_BY_CID_FAIL = 'GET_SUB_CATEGORY_BY_CID_FAIL';
// contact
export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL';
// lastestPost
export const GET_LASTEST_POST = 'GET_LASTEST_POST';
export const GET_LASTEST_POST_SUCCESS = 'GET_LASTEST_POST_SUCCESS';
export const GET_LASTEST_POST_FAIL = 'GET_LASTEST_POST_FAIL';

export const GET_LASTEST_POST_BY_SCID = 'GET_LASTEST_POST_BY_SCID';
export const GET_LASTEST_POST_BY_SCID_SUCCESS =
  'GET_LASTEST_POST_BY_SCID_SUCCESS';
export const GET_LASTEST_POST_BY_SCID_FAIL = 'GET_LASTEST_POST_BY_SCID_FAIL';
// postBySubCategory
export const GET_LASTEST_POST_BSC = 'GET_LASTEST_POST_BSC';
export const GET_LASTEST_POST_BSC_SUCCESS = 'GET_LASTEST_POST_BSC_SUCCESS';
export const GET_LASTEST_POST_BSC_FAIL = 'GET_LASTEST_POST_BSC_FAIL';
