// forum post
export const GET_FORUM_POST = 'GET_FORUM_POST';
export const GET_FORUM_POST_SUCCESS = 'GET_FORUM_POST_SUCCESS';
export const GET_FORUM_POST_FAIL = 'GET_FORUM_POST_FAIL';

export const CREATE_FORUM_POST = 'CREATE_FORUM_POST';
export const CREATE_FORUM_POST_SUCCESS = 'CREATE_FORUM_POST_SUCCESS';
export const CREATE_FORUM_POST_FAIL = 'CREATE_FORUM_POST_FAIL';
