#---
# Create Namespace for Feature
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: bms-new-dev
#  labels:
#    field.cattle.io/projectId: p-qgsx8
#  annotations:
#    field.cattle.io/projectId: local:p-qgsx8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-label-name
spec:
  selector:
    matchLabels:
      app: k8s-label-name
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-label-name
    spec:
      containers:
        - name: k8s-label-name
          image: k8s-registry-image
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
      imagePullSecrets:
        - name: registry-cred
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-label-name
spec:
  selector:
    app: k8s-label-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: k8s-expose
  type: NodePort
