export const GET_POS_GEO = 'GET_POS_GEO';
export const GET_POS_GEO_SUCCESS = 'GET_POS_GEO_SUCCESS';
export const GET_POS_GEO_FAIL = 'GET_POS_GEO_FAIL';
// epidemicHistory
export const COUNT_EPIDEMIC = 'COUNT_EPIDEMIC';
export const COUNT_EPIDEMIC_SUCCESS = 'COUNT_EPIDEMIC_SUCCESS';
export const COUNT_EPIDEMIC_FAIL = 'COUNT_EPIDEMIC_FAIL';
