// epidemic
export const GET_EPIDEMIC = 'GET_EPIDEMIC';
export const GET_EPIDEMIC_SUCCESS = 'GET_EPIDEMIC_SUCCESS';
export const GET_EPIDEMIC_FAIL = 'GET_EPIDEMIC_FAIL';
// epidemicHistory
export const GET_EPIDEMIC_HISTORY = 'GET_EPIDEMIC_HISTORY';
export const GET_EPIDEMIC_HISTORY_SUCCESS = 'GET_EPIDEMIC_HISTORY_SUCCESS';
export const GET_EPIDEMIC_HISTORY_FAIL = 'GET_EPIDEMIC_HISTORY_FAIL';

export const UPDATE_EPIDEMIC_HISTORY = 'UPDATE_EPIDEMIC_HISTORY';
export const UPDATE_EPIDEMIC_HISTORY_SUCCESS =
  'UPDATE_EPIDEMIC_HISTORY_SUCCESS';
export const UPDATE_EPIDEMIC_HISTORY_FAIL = 'UPDATE_EPIDEMIC_HISTORY_FAIL';

export const CREATE_EPIDEMIC_HISTORY = 'CREATE_EPIDEMIC_HISTORY';
export const CREATE_EPIDEMIC_HISTORY_SUCCESS =
  'CREATE_EPIDEMIC_HISTORY_SUCCESS';
export const CREATE_EPIDEMIC_HISTORY_FAIL = 'CREATE_EPIDEMIC_HISTORY_FAIL';
// plant
export const GET_PLANT = 'GET_PLANT';
export const GET_PLANT_SUCCESS = 'GET_PLANT_SUCCESS';
export const GET_PLANT_FAIL = 'GET_PLANT_FAIL';

export const CREATE_PLANT = 'CREATE_PLANT';
export const CREATE_PLANT_SUCCESS = 'CREATE_PLANT_SUCCESS';
export const CREATE_PLANT_FAIL = 'CREATE_PLANT_FAIL';

export const UPDATE_PLANT = 'UPDATE_PLANT';
export const UPDATE_PLANT_SUCCESS = 'UPDATE_PLANT_SUCCESS';
export const UPDATE_PLANT_FAIL = 'UPDATE_PLANT_FAIL';

export const DELETE_PLANT = 'DELETE_PLANT';
export const DELETE_PLANT_SUCCESS = 'DELETE_PLANT_SUCCESS';
export const DELETE_PLANT_FAIL = 'DELETE_PLANT_FAIL';
// genusFeature
export const GET_GENUS_FEATURE = 'GET_GENUS_FEATURE';
export const GET_GENUS_FEATURE_SUCCESS = 'GET_GENUS_FEATURE_SUCCESS';
export const GET_GENUS_FEATURE_FAIL = 'GET_GENUS_FEATURE_FAIL';
