/*
 *
 * Admin constants
 *
 */

// user
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
// userType
export const GET_USER_TYPE = 'GET_USER_TYPE';
export const GET_USER_TYPE_SUCCESS = 'GET_USER_TYPE_SUCCESS';
export const GET_USER_TYPE_FAIL = 'GET_USER_TYPE_FAIL';
// post
export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const COUNT_POST = 'COUNT_POST';
export const COUNT_POST_SUCCESS = 'COUNT_POST_SUCCESS';
export const COUNT_POST_FAIL = 'COUNT_POST_FAIL';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
// subCategory
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_SUB_CATEGORY_SUCCESS = 'GET_SUB_CATEGORY_SUCCESS';
export const GET_SUB_CATEGORY_FAIL = 'GET_SUB_CATEGORY_FAIL';
// status
export const GET_STATUS = 'GET_STATUS';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';
// problem
export const GET_PROBLEM = 'GET_PROBLEM';
export const GET_PROBLEM_SUCCESS = 'GET_PROBLEM_SUCCESS';
export const GET_PROBLEM_FAIL = 'GET_PROBLEM_FAIL';

export const COUNT_PROBLEM = 'COUNT_PROBLEM';
export const COUNT_PROBLEM_SUCCESS = 'COUNT_PROBLEM_SUCCESS';
export const COUNT_PROBLEM_FAIL = 'COUNT_PROBLEM_FAIL';

export const UPDATE_PROBLEM = 'UPDATE_PROBLEM';
export const UPDATE_PROBLEM_SUCCESS = 'UPDATE_PROBLEM_SUCCESS';
export const UPDATE_PROBLEM_FAIL = 'UPDATE_PROBLEM_FAIL';

export const DELETE_PROBLEM = 'DELETE_PROBLEM';
export const DELETE_PROBLEM_SUCCESS = 'DELETE_PROBLEM_SUCCESS';
export const DELETE_PROBLEM_FAIL = 'DELETE_PROBLEM_FAIL';
// province
export const GET_PROVINCE = 'GET_PROVINCE';
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_FAIL = 'GET_PROVINCE_FAIL';

export const GET_CENTER = 'GET_CENTER';
export const GET_CENTER_SUCCESS = 'GET_CENTER_SUCCESS';
export const GET_CENTER_FAIL = 'GET_CENTER_FAIL';
// contact
export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL';

export const CREATE_CONTACT = 'CREATE_CONTACT';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAIL = 'UPDATE_CONTACT_FAIL';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';
// minio
export const UPLOAD_IMG = 'UPLOAD_IMG';
export const UPLOAD_IMG_SUCCESS = 'UPLOAD_IMG_SUCCESS';
export const UPLOAD_IMG_FAIL = 'UPLOAD_IMG_FAIL';

export const UPLOAD_PDF = 'UPLOAD_PDF';
export const UPLOAD_PDF_SUCCESS = 'UPLOAD_PDF_SUCCESS';
export const UPLOAD_PDF_FAIL = 'UPLOAD_PDF_FAIL';
// households
export const GET_HOUSEHOLD = 'GET_HOUSEHOLD';
export const GET_HOUSEHOLD_SUCCESS = 'GET_HOUSEHOLD_SUCCESS';
export const GET_HOUSEHOLD_FAIL = 'GET_HOUSEHOLD_FAIL';

export const COUNT_HOUSEHOLD = 'COUNT_HOUSEHOLD';
export const COUNT_HOUSEHOLD_SUCCESS = 'COUNT_HOUSEHOLD_SUCCESS';
export const COUNT_HOUSEHOLD_FAIL = 'COUNT_HOUSEHOLD_FAIL';

export const CREATE_HOUSEHOLD = 'CREATE_HOUSEHOLD';
export const CREATE_HOUSEHOLD_SUCCESS = 'CREATE_HOUSEHOLD_SUCCESS';
export const CREATE_HOUSEHOLD_FAIL = 'CREATE_HOUSEHOLD_FAIL';

export const UPDATE_HOUSEHOLD = 'UPDATE_HOUSEHOLD';
export const UPDATE_HOUSEHOLD_SUCCESS = 'UPDATE_HOUSEHOLD_SUCCESS';
export const UPDATE_HOUSEHOLD_FAIL = 'UPDATE_HOUSEHOLD_FAIL';

export const DELETE_HOUSEHOLD = 'DELETE_HOUSEHOLD';
export const DELETE_HOUSEHOLD_SUCCESS = 'DELETE_HOUSEHOLD_SUCCESS';
export const DELETE_HOUSEHOLD_FAIL = 'DELETE_HOUSEHOLD_FAIL';
// land
export const GET_LAND = 'GET_LAND';
export const GET_LAND_SUCCESS = 'GET_LAND_SUCCESS';
export const GET_LAND_FAIL = 'GET_LAND_FAIL';

// plants
export const GET_PLANT = 'GET_PLANT';
export const GET_PLANT_SUCCESS = 'GET_PLANT_SUCCESS';
export const GET_PLANT_FAIL = 'GET_PLANT_FAIL';

export const CREATE_PLANT = 'CREATE_PLANT';
export const CREATE_PLANT_SUCCESS = 'CREATE_PLANT_SUCCESS';
export const CREATE_PLANT_FAIL = 'CREATE_PLANT_FAIL';

export const UPDATE_PLANT = 'UPDATE_PLANT';
export const UPDATE_PLANT_SUCCESS = 'UPDATE_PLANT_SUCCESS';
export const UPDATE_PLANT_FAIL = 'UPDATE_PLANT_FAIL';

export const DELETE_PLANT = 'DELETE_PLANT';
export const DELETE_PLANT_SUCCESS = 'DELETE_PLANT_SUCCESS';
export const DELETE_PLANT_FAIL = 'DELETE_PLANT_FAIL';
// genusFeature
export const GET_GENUS_FEATURE = 'GET_GENUS_FEATURE';
export const GET_GENUS_FEATURE_SUCCESS = 'GET_GENUS_FEATURE_SUCCESS';
export const GET_GENUS_FEATURE_FAIL = 'GET_GENUS_FEATURE_FAIL';
// banner
export const GET_BANNER = 'GET_BANNER';
export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS';
export const GET_BANNER_FAIL = 'GET_BANNER_FAIL';

export const UPDATE_BANNER = 'UPDATE_BANNER';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_FAIL = 'UPDATE_BANNER_FAIL';
// document
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';
export const GET_DOCUMENT_FAIL = 'GET_DOCUMENT_FAIL';

export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_FAIL = 'CREATE_DOCUMENT_FAIL';

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_FAIL = 'UPDATE_DOCUMENT_FAIL';

export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAIL = 'DELETE_DOCUMENT_FAIL';
// documentType
export const GET_DOCUMENT_TYPE = 'GET_DOCUMENT_TYPE';
export const GET_DOCUMENT_TYPE_SUCCESS = 'GET_DOCUMENT_TYPE_SUCCESS';
export const GET_DOCUMENT_TYPE_FAIL = 'GET_DOCUMENT_TYPE_FAIL';
// field
export const GET_FIELD = 'GET_FIELD';
export const GET_FIELD_SUCCESS = 'GET_FIELD_SUCCESS';
export const GET_FIELD_FAIL = 'GET_FIELD_FAIL';
