export const GET_DOCUMENT = 'GET_DOCUMENT';
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS';
export const GET_DOCUMENT_FAIL = 'GET_DOCUMENT_FAIL';

export const GET_DOCUMENT_INFORMATION = 'GET_DOCUMENT_INFORMATION';
export const GET_DOCUMENT_INFORMATION_SUCCESS =
  'GET_DOCUMENT_INFORMATION_SUCCESS';
export const GET_DOCUMENT_INFORMATION_FAIL = 'GET_DOCUMENT_INFORMATION_FAIL';
